language: c
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get install -qq make
  - . pre.sh
  - . ../../build.sh
  - openssl genrsa -out server.key 512 # make OREORE crt to success nginx -t
  - echo jp > expect
  - for i in `seq 1 10`; echo >> expect
  - cat expect | openssl req -new -key server.key -out server.csr
  - openssl x509 -days 3650 -req -signkey server.key -in server.csr -out server.crt
  - sudo mv server.crt /etc/nginx/ssl/server.crt
  - sudo mv server.key /etc/nginx/ssl/server.key
  - sudo cp nginx.conf /etc/nginx/nginx.conf
script:
  - sudo /opt/nginx/sbin/nginx -t
